// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace AzureWebApp.Models
{
    public partial class User
    {
        private string _email;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Email
        {
            get { return this._email; }
            set { this._email = value; }
        }
        
        private string _firstname;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Firstname
        {
            get { return this._firstname; }
            set { this._firstname = value; }
        }
        
        private string _lastname;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Lastname
        {
            get { return this._lastname; }
            set { this._lastname = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the User class.
        /// </summary>
        public User()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the User class with required
        /// arguments.
        /// </summary>
        public User(string firstname, string lastname, string email)
            : this()
        {
            if (firstname == null)
            {
                throw new ArgumentNullException("firstname");
            }
            if (lastname == null)
            {
                throw new ArgumentNullException("lastname");
            }
            if (email == null)
            {
                throw new ArgumentNullException("email");
            }
            this.Firstname = firstname;
            this.Lastname = lastname;
            this.Email = email;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken emailValue = inputObject["Email"];
                if (emailValue != null && emailValue.Type != JTokenType.Null)
                {
                    this.Email = ((string)emailValue);
                }
                JToken firstnameValue = inputObject["Firstname"];
                if (firstnameValue != null && firstnameValue.Type != JTokenType.Null)
                {
                    this.Firstname = ((string)firstnameValue);
                }
                JToken lastnameValue = inputObject["Lastname"];
                if (lastnameValue != null && lastnameValue.Type != JTokenType.Null)
                {
                    this.Lastname = ((string)lastnameValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type User
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Email == null)
            {
                throw new ArgumentNullException("Email");
            }
            if (this.Firstname == null)
            {
                throw new ArgumentNullException("Firstname");
            }
            if (this.Lastname == null)
            {
                throw new ArgumentNullException("Lastname");
            }
            if (this.Email != null)
            {
                outputObject["Email"] = this.Email;
            }
            if (this.Firstname != null)
            {
                outputObject["Firstname"] = this.Firstname;
            }
            if (this.Lastname != null)
            {
                outputObject["Lastname"] = this.Lastname;
            }
            return outputObject;
        }
    }
}
