// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AzureWebApp;
using Microsoft.Rest;

namespace AzureWebApp
{
    public static partial class MailExtensions
    {
        /// <param name='operations'>
        /// Reference to the AzureWebApp.IMail.
        /// </param>
        /// <param name='message'>
        /// Required.
        /// </param>
        public static object SendMailByMessage(this IMail operations, string message)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IMail)s).SendMailByMessageAsync(message);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the AzureWebApp.IMail.
        /// </param>
        /// <param name='message'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> SendMailByMessageAsync(this IMail operations, string message, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.SendMailByMessageWithOperationResponseAsync(message, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
