// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using AzureWebApp;
using Microsoft.Rest;

namespace AzureWebApp
{
    public partial class Meetuphh : ServiceClient<Meetuphh>, IMeetuphh
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IMail _mail;
        
        public virtual IMail Mail
        {
            get { return this._mail; }
        }
        
        private IUserOperations _user;
        
        public virtual IUserOperations User
        {
            get { return this._user; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Meetuphh class.
        /// </summary>
        public Meetuphh()
            : base()
        {
            this._mail = new Mail(this);
            this._user = new UserOperations(this);
            this._baseUri = new Uri("https://microsoft-apiapp21ee0a3b45e043e58aa5068ad2488263.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the Meetuphh class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Meetuphh(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._mail = new Mail(this);
            this._user = new UserOperations(this);
            this._baseUri = new Uri("https://microsoft-apiapp21ee0a3b45e043e58aa5068ad2488263.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the Meetuphh class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Meetuphh(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._mail = new Mail(this);
            this._user = new UserOperations(this);
            this._baseUri = new Uri("https://microsoft-apiapp21ee0a3b45e043e58aa5068ad2488263.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the Meetuphh class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Meetuphh(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the Meetuphh class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Meetuphh(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the Meetuphh class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Meetuphh(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
